# Generated by Django 2.2.12 on 2022-05-30 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '咨询'), (2, '公司动态'), (3, '分享'), (4, '答疑'), (5, '其他')], verbose_name='分类')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('image', models.CharField(max_length=128, verbose_name='图片路径')),
                ('summary', models.CharField(max_length=255, verbose_name='简介')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读数')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Article', verbose_name='文章')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.Comment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.UserInfo', verbose_name='评论者')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='art.Article', verbose_name='文章')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.UserInfo', verbose_name='作者'),
        ),
    ]
