# Generated by Django 2.2.12 on 2022-06-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_userinfo_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='token',
        ),
    ]
